workflows:
  my-workflow:
    name: Hello script practice
    instance_type: mac_mini_m2
    max_build_duration: 60
    inputs:
      name:
        description: Input description
        default: Codemagic
    enviroment:
      flutter: stable
      xcode: latest
      cocoapods: 1.15.2
      ruby: 3.0.0
