workflows:
  my-workflow:
    name: Hello script practice
    instance_type: mac_mini_m2
    max_build_duration: 60
    inputs:
      name:
        description: Input description
        default: Codemagic